openapi: 3.2.0
info:
  contact:
    email: support@r2capital.co
    name: R2 Support
  description: '## Introduction


    Through our REST APIs, you''ll be able to run an end-to-end capital program for your merchants.'
  title: R2 Callbacks API
  version: '0.1'
servers:
- url: https://gateway-dev.r2capital.co:443/v2
- url: https://gateway-dev.r2capital.co/v2/
  description: Development environment (DEV)
tags:
- name: Callbacks
paths:
  /callbacks/{id}:
    get:
      parameters:
      - description: uuid formatted ID.
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  error:
                    type: string
                  items:
                    items:
                      $ref: '#/components/schemas/callbacks.Callback'
                    type: array
                type: object
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      security:
      - JWT: []
      summary: Show a callback by its id as filtering key
      tags:
      - Callbacks
      operationId: getCallbacksById
      x-operation-id-source: derived
    put:
      parameters:
      - description: uuid formatted ID.
        in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/callbacks.CallbackRequestArray'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  error:
                    type: string
                  items:
                    items:
                      $ref: '#/components/schemas/callbacks.Callback'
                    type: array
                type: object
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      security:
      - JWT: []
      summary: Update a callback
      tags:
      - Callbacks
      operationId: putCallbacksById
      x-operation-id-source: derived
  /callbacks/:
    get:
      description: Show a list of callbacks associated to the partner using the given filtering params.
      parameters:
      - in: query
        name: page
        schema:
          type: integer
      - in: query
        name: per_page
        schema:
          type: integer
      - in: query
        name: sort
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  error:
                    type: string
                  items:
                    items:
                      $ref: '#/components/schemas/callbacks.Callback'
                    type: array
                type: object
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      security:
      - JWT: []
      summary: Show all callbacks
      tags:
      - Callbacks
      operationId: getCallbacks
      x-operation-id-source: derived
    post:
      description: 'Important: It only allows callbacks from one unique financing each time.'
      requestBody:
        $ref: '#/components/requestBodies/callbacks.CallbackRequestArray'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                properties:
                  error:
                    type: string
                  items:
                    items:
                      $ref: '#/components/schemas/callbacks.Callback'
                    type: array
                type: object
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      security:
      - JWT: []
      summary: Add a new callback
      tags:
      - Callbacks
      operationId: postCallbacks
      x-operation-id-source: derived
components:
  requestBodies:
    callbacks.CallbackRequestArray:
      content:
        application/json:
          schema:
            items:
              $ref: '#/components/schemas/callbacks.CallbackRequest'
            type: array
      description: callback data
      required: true
  schemas:
    callbacks.CallbackRequest:
      properties:
        url:
          type: string
      type: object
    callbacks.Callback:
      properties:
        created_at:
          type: string
        id:
          type: string
        updated_at:
          type: string
        url:
          type: string
      type: object
  securitySchemes:
    JWT:
      in: header
      name: Authorization
      type: apiKey
