openapi: 3.2.0
info:
  contact:
    email: support@r2capital.co
    name: R2 Support
  description: '## Introduction


    Through our REST APIs, you''ll be able to run an end-to-end capital program for your merchants.'
  title: R2 Events API
  version: '0.1'
servers:
- url: https://gateway-dev.r2capital.co:443/v2
- url: https://gateway-dev.r2capital.co/v2/
  description: Development environment (DEV)
tags:
- name: Events
paths:
  /events/{id}:
    get:
      parameters:
      - description: uuid formatted ID.
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  error:
                    type: string
                  items:
                    items:
                      $ref: '#/components/schemas/events.EventWrite'
                    type: array
                type: object
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      security:
      - JWT: []
      summary: Show a callback by its id as filtering key
      tags:
      - Events
      operationId: getEventsById
      x-operation-id-source: derived
components:
  schemas:
    events.EventWrite:
      properties:
        data:
          type: object
        id:
          type: string
        kind:
          type: string
        stream_id:
          type: string
        stream_kind:
          type: string
        timestamp:
          type: string
        transition:
          $ref: '#/components/schemas/events.Transition'
        version:
          default: 1
          type: integer
      type: object
    events.Transition:
      properties:
        client:
          type: string
        from:
          type: string
        to:
          type: string
        user:
          description: systemx
          type: string
      type: object
  securitySchemes:
    JWT:
      in: header
      name: Authorization
      type: apiKey
